### ISSUE TITLE
Avoid read-only properties, make a method that return the value instead

### ISSUE THREAD

**Issue by NSElvis** [hyperoslo/objective-c-style-guide#30]

**Comment by zenangst** [comment]
So instead of declaring properties in the header, you should instead provide a method for returning private properties?

**Comment by NSElvis** [comment]
Only for properties that are readonly

So instead of:

`@property (nonatomic, readonly, getter=isLoading) BOOL loading;`

You do 

`- (BOOL)isLoading;`

**Comment by kostiakoval** [comment]
Apple is mowing more to property style. 
see  "Using @property" part

http://devstreaming.apple.com/videos/wwdc/2014/202xx3ane09vxdz/202/202_whats_new_in_cocoa_touch.pdf?dl=1
https://developer.apple.com/videos/wwdc/2014/#202

So would suggest to think a bit more about this one

**Comment by NSElvis** [comment]
@kostiakoval Which page?

I suggest the method approach since you shouldn't have to relay on the compiler or jumping to the class header to know that a property is `readonly`.

You should be able to tell just by looking at the source code.

For example:

Is `user.disabled` readonly? 

Is `[user disabled]` readonly?

**Comment by zenangst** [comment]
@NSElvis good point! For me, as a default, properties kind of imply that they are mutable.

**Comment by kostiakoval** [comment]
Ups, wrong link, I've updated them, check once more, Session 204

**Comment by NSElvis** [comment]
@kostiakoval: I've seen it but I still don't get what you mean.

>Apple is mowing more to property style. 
see "Using @property" part
So would suggest to think a bit more about this one

**Comment by NSElvis** [comment]
@kostiakoval Nevermind, this was stupid, closing issue. :)
